//Auth Action
export const LOADING = 'LOADING';
export const HOME = 'HOME';
export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const RESEND_OTP = 'RESEND_OTP';
export const VALIDATE_USERNAME = 'VALIDATE_USERNAME';
export const VALIDATE_PASSWORD = 'VALIDATE_PASSWORD';
export const VALIDATE_FORGOTPASSWORD_OTP = 'VALIDATE_FORGOTPASSWORD_OTP';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const USERNAME = 'USERNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const GET_COUNTRY_DETAILS = 'GET_COUNTRY_DETAILS';
export const FORGOT_USERNAME = 'FORGOT_USERNAME';
export const RESEND_OTP_FORGOT_PASSWORD = 'RESEND_OTP_FORGOT_PASSWORD';
export const GET_INTER_OVERVIEW = 'GET_INTER_OVERVIEW';
export const GET_DECISION = 'GET_DECISION';
export const GET_VISA = 'GET_VISA';
export const GET_SERVICECENTER = 'GET_SERVICECENTER';
export const GET_RULE = 'GET_RULE';
export const CREATE_POST = 'CREATE_POST';
export const GET_REASON = 'GET_REASON';

//Notification Action
export const NOTIFICATION_STATUS = 'NOTIFICATION_STATUS';
export const SEND_NOTIFICATION_STATUS = 'SEND_NOTIFICATION_STATUS';
export const UPDATE_LINK_STATUS = 'UPDATE_LINK_STATUS';

//Timeline Action(Dashboard)
export const GET_OTH_SUPT_APP_DATA = 'GET_OTH_SUPT_APP_DATA';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';

//My Account
export const UPDATE_PERSONAL_DETAILS = 'UPDATE_PERSONAL_DETAILS';
export const GET_BEN_FAMILY_INFO = 'GET_BEN_FAMILY_INFO';
export const GET_FAMILY_TYPE = 'GET_FAMILY_TYPE';
export const GET_INDIVISUAL_FAMILY_INFO = 'GET_INDIVISUAL_FAMILY_INFO';
export const GET_BEN_DOC = 'GET_BEN_DOC';
export const FETCH_STATE_LIST = 'FETCH_STATE_LIST';
export const GET_INDIVISUAL_BENEFICIARY_INFO =
  'GET_INDIVISUAL_BENEFICIARY_INFO';
export const FETCH_COUNTRY_LIST = 'FETCH_COUNTRY_LIST';
export const EMPTYPE = 'EMPTYPE';
export const CURR = 'CURR';
export const GETEXPERIENCE_DETAILS = 'GETEXPERIENCE_DETAILS';
export const UPDATE_EXPERIENCE_DETAILS = 'UPDATE_EXPERIENCE_DETAILS';
export const DELETE_EXPERIENCE_DETAILS = 'DELETE_EXPERIENCE_DETAILS';
export const POST_PERSONAL_DETAILS = 'POST_PERSONAL_DETAILS';
export const FETCH_DEGREE = 'FETCH_DEGREE';
export const SEND_EDUCATION_INFO = 'SEND_EDUCATION_INFO';
export const GET_EDUCATIONAL_INFO = 'GET_EDUCATIONAL_INFO';
export const GET_TRAINING_INFO = 'GET_TRAINING_INFO';
export const SEND_TRAINING_INFO = 'SEND_TRAINING_INFO';
export const SEND_CERTIFICATIONS_INFO = 'SEND_CERTIFICATIONS_INFO';
export const GET_CERTIFICATIONS_INFO = 'GET_CERTIFICATIONS_INFO';
export const GET_EDUCDOC_INFO = 'GET_EDUCDOC_INFO';
export const DELETE_EXPERIENCE_DOC = 'DELETE_EXPERIENCE_DOC';
export const DELETE_EDUC_INFO = 'DELETE_EDUC_INFO';
export const GET_TRGCDOC_INFO = 'GET_TRGCDOC_INFO';
export const GET_LICCDOC_INFO = 'GET_LICCDOC_INFO';
export const DELETE_REL_DOC = 'DELETE_REL_DOC';
export const DELETE_LIC_INFO = 'DELETE_LIC_INFO';
export const DELETE_TRG_INFO = 'DELETE_TRG_INFO';
export const IMMIGRATION_TRAVEL_HISTORY = 'IMMIGRATION_TRAVEL_HISTORY';
export const GET_IMMIGRATION_TRAVEL_HISTORY = 'GET_IMMIGRATION_TRAVEL_HISTORY';
export const VISA_TYPE = 'VISA_TYPE';
export const PET_TYPE = 'PET_TYPE';
export const VSAOUT_TYPE = 'VSAOUT_TYPE';
export const GET_SELF = 'GET_SELF';
export const POST_SELF = 'POST_SELF';
export const DELETE_SELF = 'DELETE_SELF';
export const POST_IMMIGRATION_STATUS = 'POST_IMMIGRATION_STATUS';
export const GET_IMMIGRATION_STATUS = 'GET_IMMIGRATION_STATUS';
export const IMMI_DOC_TYPE = 'IMMI_DOC_TYPE';
export const DELETE_IMMI_DOC = 'DELETE_IMMI_DOC';
export const PASSPORT_DOC = 'PASSPORT_DOC';
export const DELETE_US_TRAVEL_HISTORY = 'DELETE_US_TRAVEL_HISTORY';
export const GET_PROFILE_STATUS = 'GET_PROFILE_STATUS';
export const GREENCARD_DOC = 'GREENCARD_DOC';
export const GET_BEN_TYPE = 'GET_BEN_TYPE';
export const FETCH_BUSINESS_TYPE = 'FETCH_BUSINESS_TYPE';
export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_ROLE_LIST = 'GET_ROLE_LIST';
export const GET_NOTIFICATION_SETTINGS = 'GET_NOTIFICATION_SETTINGS';
export const GET_POLICY_LIST = 'GET_POLICY_LIST';
export const FETCH_VISA_LIST = 'FETCH_VISA_LIST';

//Delete Account
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
//Account Status
export const GET_BENEFICIARY_ACCOUNT_STATUS = 'GET_BENEFICIARY_ACCOUNT_STATUS';
//Update Account Status
export const UPDATE_BENEFICIARY_ACCOUNT_STATUS =
  'UPDATE_BENEFICIARY_ACCOUNT_STATUS';

//Petition Decisions
export const GET_PETITION_DECISION = 'GET_PETITION_DECISION';
export const GET_PETITION_DECISION_ALL_COMMENTS =
  'GET_PETITION_DECISION_ALL_COMMENTS';
export const DECISION_POST_UPVOTE = 'DECISION_POST_UPVOTE';
export const GET_IMM_RULE = 'GET_IMM_RULE';
export const GET_STORY = 'GET_STORY';
//Community Card
export const FOLLOW_POST = 'FOLLOW_POST';
export const FOVOURITE_POST = 'FOVOURITE_POST';
export const COMMENT_POST = 'COMMENT_POST';
export const COMMENT_UPVOTE = 'COMMENT_UPVOTE';
export const COMMENT_DELETE = 'COMMENT_DELETE';
export const POST_DELETE = 'POST_DELETE';
export const COMMENT_VIEW_COUNT = 'COMMENT_VIEW_COUNT';
